version: '3'

services:
  mysql:
    image: mysql:5
    env_file: .env

  backend:
    build: backend
    image: leadcoin/backend
    env_file: .env
    ports:
      - '3001:3000'
    volumes:
      - './backend/app:/usr/src/app'
      - './backend/test:/usr/src/test'
    command: 'npm start'
